name: Build and test
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout application code
        uses: actions/checkout@v4
      - name: setup GO
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.7'
      - name: Build Application
        run: |
          make build
      - name: Test
        run: make test
    
      - name: generate changelog
        run: |
          git log --oneline --decorate --no-merges > changelog.txt
      - name: create release
        uses: goreleaser/goreleaser-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          args: release --rm-dist
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          artifact: ./path/to/artifact
          tag: ${{ github.ref_name }}
      - name: s2i Build and Push
        run: |
          sudo docker login -u sanket -p ${{ secrets.PASSWORD }} quay.io 
          make s2i-push