name: Build and test
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  
   

jobs:
  my_job:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout application code
        uses: actions/checkout@v4
      - name: setup GO
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.7'
      - name: Build Application
        run: |
          make build
      - name: Test
        run: make test
      - name: Create release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create avg-${{ github.ref_name }}-x86_64 \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
      - name: Upload Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release upload avg-${{ github.ref_name }}-x86_64 ${{ env.BIN_PATH }} --clobber
      - name: s2i Build and Push
        run: |
          sudo docker login -u sanket -p ${{ secrets.PASSWORD }} quay.io 
          make s2i-push
        
        
  
