name: Build and test
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  
   

jobs:
  my_job:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout application code
        uses: actions/checkout@v4
      - name: setup GO
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.7'
      - name: Build Application
        run: |
          make build
      - name: Test
        run: make test
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      - name: s2i Build and Push
        run: |
          sudo docker login -u sanket -p ${{ secrets.PASSWORD }} quay.io 
          make s2i-push
        
        
  
