name: Build and test
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout application code
        uses: actions/checkout@v4
      - name: setup GO
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.7'
      - name: Build Application
        run: |
          make build
      - name: Test
        run: make test
    
      - name: generate changelog
        run: |
          
          PREVIOUS_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))
          git log --oneline --decorate --first-parent ${PREVIOUS_TAG}.. > changelog.txt
      - name: Create release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create avg-${{ github.ref_name }}-x86_64 \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
            --notes-file changelog.txt \
            
      - name: Upload Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          RELEASE_ID=$(gh release view --repo="$GITHUB_REPOSITORY" --json id --jq '.id')
          ARTIFACT_PATH=${GITHUB_WORKSPACE}/path/to/artifact
          gh release upload "$RELEASE_ID" --clobber --repo="$GITHUB_REPOSITORY" "$ARTIFACT_PATH"
      - name: s2i Build and Push
        run: |
          sudo docker login -u sanket -p ${{ secrets.PASSWORD }} quay.io 
          make s2i-push